forked from codeberg https://codeberg.org/useless-utils/mpd-current-json
adds filename to the json along with the mpd playlist ids for songs.
i want to add the rest of it but chatgpt sucks at haskell and i only know bash so it was slow going just to add the file name.  
the IDs were surprisingly worse.

#+TITLE: Print currently playing MPD's song metadata and status as JSON
# #+PROPERTY: header-args :comments org
#+OPTIONS: toc:1

I probably should have kept a better record of this, but I THINK all that's required is 
- clone it
- cd to it
- apt install cabal-install
- cabal update
- cabal init
- cabal install

it's possible you have to for the original first and then just copy over Main.hs.  i dunno, the executable works right now so...



* Installation instructions aren't going to work for this fork.
: cabal install mpd-current-json
or
#+begin_example
git clone https://codeberg.org/useless-utils/mpd-current-json
cd mpd-current-json
#+end_example
and to install the executable to =./dist=, in the current directory:
: cabal install --install-method=copy --overwrite-policy=always --installdir=dist
or to install to =${CABAL_DIR}/bin= remove the =--installdir=dist=
argument. =CABAL_DIR= defaults to =~/.local/share/cabal=.

* Usage
get values
: mpd-current-json | jaq .tags.album
: mpd-current-json | jaq .status.elapsed_percent

provide host and port with
: mpd-current-json -h 'localhost' -p 4321
